[tools]
"aqua:cli/cli" = "latest"
"aqua:evilmartians/lefthook" = "latest"
"aqua:gitleaks/gitleaks" = "latest"
"aqua:go-task/task" = "latest"
"aqua:jqlang/jq" = "latest"
"conda:imagemagick" = "latest"
node = "latest"
bun = "latest"
direnv = "latest"
"npm:pyright" = "latest"
colima = "latest"
docker-cli = "latest"
shellcheck = "latest"

[tools.docker-compose]
version = "latest"
postinstall = '''
mkdir -p ~/.docker/cli-plugins ~/.local/bin
compose_plugin="$(which docker-cli-plugin-docker-compose)"
ln -sf "$compose_plugin" ~/.docker/cli-plugins/docker-compose
ln -sf "$compose_plugin" ~/.local/bin/docker-compose
'''
