---
name: Wikipedia Current Events
strategy: polling
polling_verb: get
polling_url: |
  https://en.wikipedia.org/w/api.php?action=parse&page=Portal%3ACurrent%20events%2F{{ "now" | date: "%Y" }}%20{{ "now" | date: "%B" }}%20{{ "now" | date: "%-d" }}&prop=wikitext&format=json&formatversion=2
polling_headers: |
  Accept: application/json
  User-Agent: trmnl-larapaper-wikipedia-recipe
refresh_interval: 900
no_screen_padding: "yes"
dark_mode: "no"
framework_version: 2.0
