---
name: LDS Quotes
strategy: polling
polling_verb: get
polling_url: https://gospel-quotes.netlify.app/random?max-length=1500
refresh_interval: 60
no_screen_padding: "yes"
dark_mode: "no"
framework_version: latest
custom_fields:
  - keyname: show_title_bar
    field_type: select
    type: string
    name: Show title bar
    label: Show title bar
    description: Show the bottom title bar with recipe name and quote category.
    default: "yes"
    options:
      - "Yes": "yes"
      - "No": "no"
